OrganizatorLigii.WebUI/Controllers/PlayersController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NHibernate.Linq;
using OrganizatorLigii.Domain.Entities;
using NHSession = OrganizatorLigii.Domain.Session;

namespace OrganizatorLigii.WebUI.Controllers
{
    public class PlayersController : Controller
    {
        // GET: Players
        public ActionResult Index(int teamId)
		{
			IEnumerable<Player> players = null;
			using (var session = NHSession.OpenSession())
			using (var transaction = session.BeginTransaction())
			{
				var query = session.Query<Player>()
					.Where(x => x.Team.TeamId == teamId);
				players = query.ToList();
			}
			ViewData["TeamId"] = teamId;
			return View(players);
		}

        // GET: Players/Create
        public ActionResult Create(int teamId)
		{
			ViewData["TeamId"] = teamId;
			return View();
        }

        // POST: Players/Create
        [HttpPost]
		[ValidateAntiForgeryToken]
        public ActionResult Create(Player player, int teamId)
        {
			if (!ModelState.IsValid)
			{
				ViewData["TeamId"] = teamId;
				return View(player);
			}
            try
			{
				byte[] photo = null;
				using (var binaryReader = new BinaryReader(Request.Files[0].InputStream))
				{
					photo = binaryReader.ReadBytes(Request.Files[0].ContentLength);
				}
				player.Photo = photo;
				using (var session = NHSession.OpenSession())
				using (var transaction = session.BeginTransaction())
				{
					var team = session.Query<Team>()
						.FirstOrDefault(x => x.TeamId == teamId);
					team.TeamPlayers.Add(player);
					player.Team = team;

					session.Save(player);
					transaction.Commit();
				}
				return RedirectToAction("Details", "Teams", new { teamId });
            }
            catch(Exception ex)
			{
				ViewData["TeamId"] = teamId;
				return View();
            }
        }

        // POST: Players/Delete/5
        [HttpPost]
		[ValidateAntiForgeryToken]
        public ActionResult Delete(int playerId)
        {
			int? teamId = null;
            try
            {
				using (var session = NHSession.OpenSession())
				using (var transaction = session.BeginTransaction())
				{
					var player = session.Query<Player>()
						.Where(x => x.PlayerId == playerId)
						.Fetch(x => x.Team)
						.FirstOrDefault();
					teamId = player.Team.TeamId;
					session.Delete(player);
					transaction.Commit();
				}
			}
            catch { }
			return RedirectToAction("Details", "Teams", new { teamId });
		}
    }
}

OrganizatorLigii.WebUI/Views/Players/Create.cshtml
@using OrganizatorLigii.Domain.Entities
@using OrganizatorLigii.WebUI.Extensions
@model Player

@{
    ViewBag.Title = "Dodaj Zawodnika";
    var teamId = (int)ViewData["TeamId"];
}

@using (Html.BeginForm("Create", "Players", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.Hidden("teamId", teamId)
    <div class="form-group">
        @Html.LabelFor(m => m.FirstName)
        @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.FirstName, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.LastName)
        @Html.TextBoxFor(m => m.LastName, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.LastName, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Description)
        @Html.TextAreaFor(m => m.Description, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Description, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Position)
        @Html.TextBoxFor(m => m.Position, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Position, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.JerseyNumber)
        @Html.TextBoxFor(m => m.JerseyNumber, new { @class = "form-control", type="number", min = 1})
        @Html.ValidationMessageFor(m => m.JerseyNumber, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        <label class="btn btn-primary">
            Dodaj Fotografię <input type="file" class="form-control" name="photoStream"
                style="display: none !important;" id="upload-file-info"
                onchange="$('#upload-file-info').html(this.files[0].name)" />
        </label>
    </div>
    <input type="submit" value="Zatwierdź" class="btn btn-success" />
}

OrganizatorLigii.WebUI/Views/Players/Index.cshtml
@using OrganizatorLigii.Domain.Entities
@using OrganizatorLigii.WebUI.Extensions
@model IEnumerable<Player>

@{
    Layout = null;
    var teamId = (int)ViewData["TeamId"];
}

<div class="list-group">
    <div class="list-group-item text-center">
        @Html.ActionLink("Dodaj Zawodnika", "Create", "Players",
            new { teamId }, new { @class = "btn btn-success" })
    </div>
    @foreach (var p in Model)
    {
        <div class="list-group-item">
            <div class="container">
                <div class="row">
                    <div class="col-sm-2">
                            @Html.Image(p.Photo, "img-responsive", "", Url.Content("~/Content/photo-placeholder.png"))
                    </div>
                    <div class="col-sm-2">
                        @p.FirstName @p.LastName
                    </div>
                    <div class="col-sm-6">
                        <p><b>Pozycja: </b>@p.Position</p>
                        <p><b>Numer Koszulki: </b>@p.JerseyNumber</p>
                        @p.Description  
                    </div>
                    <div class="col-sm-1">
                        @using (Html.BeginForm("Delete", "Players"))
                        {
                            @Html.AntiForgeryToken()
                            @Html.Hidden("teamId", teamId)
                            @Html.Hidden("playerId", p.PlayerId)
                            <button type="submit" class="btn btn-danger">
                                <i class="fa fa-trash"></i>
                            </button>
                        }
                    </div>
                </div>
            </div>
        </div>
    }
</div>