OrganizatorLigii.WebUI/Controllers/LocationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OrganizatorLigii.Domain.Entities;
using NHSession = OrganizatorLigii.Domain.Session;

namespace OrganizatorLigii.WebUI.Controllers
{
    public class LocationsController : Controller
    {

        // GET: Locations
        public ActionResult Index()
        {
			ActionResult result = null;
			using (var session = NHSession.OpenSession())
			using (var transaction = session.BeginTransaction())
			{
				IEnumerable<Location> locations = session
					.Query<Location>()
					.ToList();
				result = View(locations);
			}

			return result;
		}

		public ActionResult Form(int? locationId)
		{
			ActionResult result = null;
			if(locationId != null)
			{
				using (var session = NHSession.OpenSession())
				using (var transaction = session.BeginTransaction())
				{
					var location = session
						.Query<Location>()
						.FirstOrDefault(x => x.LocationId == locationId);
					result = View(location);
				}
			}
			else
			{
				result = View();
			}

			return result;
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Write(Location location)
		{
			ActionResult result = null;
			if (!ModelState.IsValid)
			{
				result = View("Form", location);
			}
			else
			{
				using (var session = NHSession.OpenSession())
				using (var transaction = session.BeginTransaction())
				{
					session.SaveOrUpdate(location);
					transaction.Commit();
					result = RedirectToAction("Index");
				}
			}

			return result;
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Delete(int locationId)
		{
			ActionResult result = null;
			try{
				if (ModelState.IsValid)
				{
					using (var session = NHSession.OpenSession())
					using (var transaction = session.BeginTransaction())
					{
						var toDelete = session.Query<Location>()
							.FirstOrDefault(x => x.LocationId == locationId);
						session.Delete(toDelete);
						transaction.Commit();
					}
				}
			}
			catch(Exception ex)
			{
			}
			result = RedirectToAction("Index");
			return result;
		}
	}
}

OrganizatorLigii.WebUI/Views/Locations/Form.cshtml
@model OrganizatorLigii.Domain.Entities.Location

@{
    ViewBag.Title = "Form";
}
@using (Html.BeginForm("Write", "Locations"))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.LocationId)

    <div class="form-horizontal">
        <h4>@(Model?.LocationId == null || Model.LocationId == 0 ? "Stwórz" : "Edytuj") Lokację</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="col-md-10">
                <label>@Html.DisplayNameFor(model => model.Name)</label>
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-10">
                <label>@Html.DisplayNameFor(model => model.City)</label>
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-1">
                <input type="submit" value="@(Model?.LocationId == null || Model.LocationId == 0 ? "Stwórz": "Edytuj")" class="btn btn-default" />
            </div>
        </div>
    </div>
}


<div>
    @Html.ActionLink("Powrót do strony głównej", "Index")
</div>

OrganizatorLigii.WebUI/Views/Locations/Index.cshtml
@using OrganizatorLigii.Domain.Entities
@model IEnumerable<Location>
@{
    ViewBag.Title = "Home Page";
}

<div class="list-group">
    <div class="list-group-item text-center">
        @Html.ActionLink("Dodaj Lokację", "Form", null, new { @class = "btn btn-success" })
    </div>
    @foreach (var l in Model)
    {
        ViewData["LocationId"] = l.LocationId;
        <div class="list-group-item">
            <div class="container">
                <div class="row">
                    <div class="col-md-offset-3 col-md-6 text-center">
                        @l.Name, @l.City
                    </div>
                    <div class="col-md-2">
                        @Html.ActionLink("Edytuj Lokację", "Form", "Locations", new { locationId = l.LocationId }, new { @class = "btn btn-info" })
                    </div>
                    <div Class="col-md-1">
                        @using (Html.BeginForm("Delete", "Locations"))
                        {
                            @Html.AntiForgeryToken()
                            <input type="hidden" value="@l.LocationId" name="locationId" />
                            <input type="submit" value="Usuń" class="btn btn-danger" />
                        }
                    </div>
                </div>
            </div>
        </div>
    }
</div>