OrganizatorLigii.WebUI/Controllers/GamesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NHibernate.Linq;
using OrganizatorLigii.Domain.Entities;
using NHSession = OrganizatorLigii.Domain.Session;

namespace OrganizatorLigii.WebUI.Controllers
{
    public class GamesController : Controller
    {
        // GET: Games/Details/5
        public ActionResult Details(int gameId)
		{
			using (var session = NHSession.OpenSession())
			using (var transaction = session.BeginTransaction())
			{
				var game = session.Query<Game>()
					.Fetch(x => x.AwayTeam)
					.Fetch(x => x.HomeTeam)
					.FirstOrDefault(x => x.GameId == gameId);
				game.GameComments = session.Query<GameComment>()
					.Where(x => x.Game.GameId == game.GameId)
					.ToList();
				return View(game);
			}

        }

        // GET: Games/Create
        public ActionResult Create(int teamId)
        {
			ViewData["TeamId"] = teamId;
			try
			{
				using (var session = NHSession.OpenSession())
				using (var transaction = session.BeginTransaction())
				{
					var query = session.Query<Team>();
					ViewData["Teams"] = query.ToList();
				}
			}
			catch { }
			return View();
        }

        // POST: Games/Create
        [HttpPost]
		[ValidateAntiForgeryToken]
        public ActionResult Create(Game game, int teamId, bool awayGame)
		{
			ViewData["TeamId"] = teamId;
			if (!ModelState.IsValid)
			{
				using (var session = NHSession.OpenSession())
				using (var transaction = session.BeginTransaction())
				{
					var query = session.Query<Team>();
					ViewData["Teams"] = query.ToList();
					return View(game);
				}
			}
			else
			{
				try
				{
					using (var session = NHSession.OpenSession())
					using (var transaction = session.BeginTransaction())
					{
						var teams = session.Query<Team>().ToList();
						ViewData["Teams"] = teams;
						var myTeam = teams.FirstOrDefault(t => t.TeamId == teamId);
						var opponentTeam = teams.FirstOrDefault(t => t.TeamId == game.OpponentId);
						game.AwayTeam = (awayGame) ? myTeam : opponentTeam;
						game.HomeTeam = (awayGame) ? opponentTeam : myTeam;

						session.Save(myTeam);
						session.Save(opponentTeam);
						session.Save(game);
						transaction.Commit();
					}
				}
				catch (Exception ex)
				{
				}

				return RedirectToAction("Details", "Teams", new { teamId });
			}
		}

        // GET: Games/Edit/5
        public ActionResult Edit(int gameId)
        {
            return View();
        }

        // POST: Games/Edit/5
        [HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit(Game game)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // POST: Games/Delete/5
        [HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Delete(int gameId, int teamId)
        {
            try
            {
				using (var session = NHSession.OpenSession())
				using (var transaction = session.BeginTransaction())
				{
					var game = session.Query<Game>()
						.Where(g => g.GameId == gameId)
						.FirstOrDefault();

					session.CreateQuery("DELETE FROM GameComment WHERE id_meczu = :gameId")
						.SetParameter("gameId", game.GameId)
						.ExecuteUpdate();
					session.Delete(game);
					transaction.Commit();
				}
            }
            catch
            {
			}
			return RedirectToAction("Details", "Teams", new { teamId });
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult WriteComment(GameComment comment, int gameId)
		{
			ActionResult result = null;
			if (!ModelState.IsValid)
			{
			}
			else
			{
				using (var session = NHSession.OpenSession())
				using (var transaction = session.BeginTransaction())
				{
					var game = session.Query<Game>()
						.FirstOrDefault(x => x.GameId == gameId);
					comment.Game = game;
					game.GameComments.Add(comment);
					session.SaveOrUpdate(comment);
					transaction.Commit();
				}
			}
			result = RedirectToAction("Details", new {  gameId });
			return result;
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult DeleteComment(int commentId)
		{
			ActionResult result = null;
			using (var session = NHSession.OpenSession())
			using (var transaction = session.BeginTransaction())
			{
				var comment = session.Query<GameComment>()
					.Fetch(x => x.Game)
					.FirstOrDefault(x => x.GameCommentId == commentId);
				int gameId = comment.Game.GameId;
				session.Delete(comment);
				transaction.Commit();
				result = RedirectToAction("Details", new {  gameId });
			}
			return result;
		}
	}
}

OrganizatorLigii.WebUI/Views/Games/Create.cshtml
@using OrganizatorLigii.Domain.Entities
@model Game
@{
    var teamId = (int)ViewData["TeamId"];
    var teams = ViewData["Teams"] as IEnumerable<Team>;
}
@using (Html.BeginForm("Create", "Games", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.Hidden("teamId", teamId)
    <div class="form-group">
        @Html.LabelFor(m => m.GameDate)
        @Html.TextBoxFor(m => m.GameDate, new { @class = "form-control", type = "date" })
        @Html.ValidationMessageFor(m => m.GameDate, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.HomeTeamScore)
        @Html.TextBoxFor(m => m.HomeTeamScore, new { @class = "form-control", type = "number", min = 0 })
        @Html.ValidationMessageFor(m => m.HomeTeamScore, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.AwayTeamScore)
        @Html.TextBoxFor(m => m.AwayTeamScore, new { @class = "form-control", type = "number", min = 0 })
        @Html.ValidationMessageFor(m => m.AwayTeamScore, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        <label>Przeciwna Drużyna</label>
        <select name="OpponentId" class="form-control">
            @foreach (var t in teams)
        {
            if (t.TeamId != teamId)
            {
                <option value="@t.TeamId">@t.Name</option>
        }
    }
        </select>
        @Html.ValidationMessageFor(m => m.OpponentId, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        <label>Gra Wyjazdowa</label>
        <input type="checkbox" value="true" name="awayGame" />
        <input type="hidden" value="false" name="awayGame" />
    </div>
    <input type="submit" value="Zatwierdź" class="btn btn-success" />
}

OrganizatorLigii.WebUI/Views/Games/Details.cshtml
@using OrganizatorLigii.Domain.Entities
@using OrganizatorLigii.WebUI.Extensions
@model Game

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["GameId"] = Model.GameId;
}
<div class="row text-center">
    <div class="col-md-2">
        @Html.Image(Model.HomeTeam.Crest, "img-responsive", "margin: 0 auto;", Url.Content("~/Content/crest-placeholder.png"))
    </div>
    <div class="col-md-2">
        <h2>
            @Model.HomeTeam.Name
        </h2>
    </div>
    <div class="col-md-1">
        <h2 class="text-primary">
            @Model.HomeTeamScore
        </h2>
    </div>
    <div class="col-md-2">
        <h2>:</h2>
    </div>
    <div class="col-md-1">
        <h2 class="text-primary">
            @Model.AwayTeamScore
        </h2>
    </div>
    <div class="col-md-2">
        <h2>
            @Model.AwayTeam.Name
        </h2>
    </div>
    <div class="col-md-2">
        @Html.Image(Model.AwayTeam.Crest, "img-responsive", "margin: 0 auto;", Url.Content("~/Content/crest-placeholder.png"))
    </div>
</div>
<hr />
<div class="row">
    <div class="container">
        <div class="row">
            <div class="col-md-offset-4 col-md-4">
                @{Html.RenderPartial("_CommentForm", new GameComment()); }
            </div>
        </div>
        <div class="row">
            <div class="col-md-offset-4 col-md-4">
                @{ Html.RenderPartial("_CommentsIndex", Model.GameComments); }
            </div>
        </div>
    </div>
</div>

OrganizatorLigii.WebUI/Views/Games/_CommentForm.cshtml
@{
    Layout = null;
}
@using OrganizatorLigii.Domain.Entities
@model GameComment

@using (Html.BeginForm("WriteComment", "Games"))
{
    @Html.AntiForgeryToken()
    <input type="hidden" value="@ViewData["GameId"]" name="gameId" />
    <div class="form-group">
        <label>Skomentuj Mecz</label>
        @Html.TextAreaFor(model => model.Text, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        <input type="submit" class="btn btn-success" value="Zatwierdź" />
    </div>
}

OrganizatorLigii.WebUI/Views/Games/_CommentsIndex.cshtml
@{
    Layout = null;
}
@using OrganizatorLigii.Domain.Entities
@model IEnumerable<GameComment>
<div class="list-group">
    @foreach (var c in Model)
    {
    <div class="list-group-item">
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    <img src="@Url.Content("~/Content/photo-placeholder.png")" class="img-circle img-responsive" />
                    <label>Anonim</label>
                </div>
                <div class="col-md-9">
                    @Html.Encode(c.Text)
                    <hr />
                    <div class="text-center">
                        @using (Html.BeginForm("DeleteComment", "Games"))
                        {
                            @Html.AntiForgeryToken()
                            <input hidden name="commentId" value="@c.GameCommentId"/>
                            <button type="submit" class="btn btn-danger">Usuń Komentarz</button>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
    }
</div>

<style>
    on-hover-display {
        display:none
    }
</style>